### ISSUE TITLE
hardcoded hostname in migrator-config.json

### ISSUE THREAD

**Issue by nouseforaname** [cloudfoundry/nats-release#46]
Hi,

our current fresh deployments break because the post start scripts are failing with:

```{"timestamp":"2022-07-13T13:49:44.786250539Z","level":"error","source":"nats-migrate","message":"nats-migrate.Failed to connect to local NATS server","data":{"error":"Error connecting: dial tcp: lookup 4e4223f3-50fd-440d-aa06-192179a1769d.nats.service.cf.internal on 169.254.0.2:53: no such host"}}```

If I'm not completely mistaken the problem seems to be that the migrator-config template uses a semi hardcoded hostname ```#{spec.id}.nats.service.cf.internal``` instead of interpolating the value of ```nats.hostname```with ```#{spec.id}```
https://github.com/cloudfoundry/nats-release/blob/6590b6da6bf812761f631e2a1fecbceb9fd719b0/jobs/nats-tls/templates/migrator-config.json.erb#L14

**Comment by reneighbor** [comment]
Thanks @nouseforaname . Fixed in https://github.com/cloudfoundry/nats-release/pull/47 and going through our CI now. I will update when the release is updated 🙏

**Comment by reneighbor** [comment]
nats-release 49 is out with a fix for this issue. Thank you for the report!
