### ISSUE TITLE
Release notes should contain NATS server version

### ISSUE THREAD

**Issue by domdom82** [cloudfoundry/nats-release#73]
Currently, the release notes don't mention the actual version within the nats-release.

The nats-server gets auto-bumped via the CI bot [automatically](https://github.com/cloudfoundry/nats-release/commit/a98b6af8afef55d6eefd6dc4e80d3c7c20a70141)

At the moment, it is tedious to look up the nats version in the [go.mod file](https://github.com/cloudfoundry/nats-release/blob/develop/src/code.cloudfoundry.org/go.mod), the version should be put on the front of each release notes as it is one most important pieces of information for the release.

**Comment by MarcPaquette** [comment]
I know @winkingturtle-vmw  has been doing a great deal of work on the CI's for this WG. 

@winkingturtle-vmw, have you gotten to the nats-release yet?

**Comment by MarcPaquette** [comment]
@tpbrisco This might be an interesting one for you.
